name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0" # Asegúrate de usar un rango compatible con la versión de Flutter que estás utilizando

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  badges: ^2.0.0 # Paquete para mostrar badges en la aplicación
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/cafe_arabica.jpg
    - assets/images/cafe_robusta.jpg
    - assets/images/cafe_colombia.jpg
    - assets/images/cafe_brasil.jpg
    - assets/images/cafe_expresso.jpg
    - assets/images/cafe_descafeinado.jpg
